/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers: never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/action-popup/': RouteRecordInfo<
      '/action-popup/',
      '/action-popup',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/action-popup/playground': RouteRecordInfo<
      '/action-popup/playground',
      '/action-popup/playground',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/common/404': RouteRecordInfo<
      '/common/404',
      '/common/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/common/about': RouteRecordInfo<
      '/common/about',
      '/common/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/common/change-log': RouteRecordInfo<
      '/common/change-log',
      '/common/change-log',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/common/features': RouteRecordInfo<
      '/common/features',
      '/common/features',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/common/help': RouteRecordInfo<
      '/common/help',
      '/common/help',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/common/privacy-policy': RouteRecordInfo<
      '/common/privacy-policy',
      '/common/privacy-policy',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/common/terms-of-service': RouteRecordInfo<
      '/common/terms-of-service',
      '/common/terms-of-service',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/content-script-iframe/': RouteRecordInfo<
      '/content-script-iframe/',
      '/content-script-iframe',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/devtools-panel/': RouteRecordInfo<
      '/devtools-panel/',
      '/devtools-panel',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/options-page/': RouteRecordInfo<
      '/options-page/',
      '/options-page',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/install': RouteRecordInfo<
      '/setup/install',
      '/setup/install',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/update': RouteRecordInfo<
      '/setup/update',
      '/setup/update',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/side-panel/': RouteRecordInfo<
      '/side-panel/',
      '/side-panel',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/ui/action-popup/pages/index.vue': {
      routes:
        | '/action-popup/'
      views:
        | never
    }
    'src/ui/action-popup/pages/playground.vue': {
      routes:
        | '/action-popup/playground'
      views:
        | never
    }
    'src/ui/common/pages/404.vue': {
      routes:
        | '/common/404'
      views:
        | never
    }
    'src/ui/common/pages/about.vue': {
      routes:
        | '/common/about'
      views:
        | never
    }
    'src/ui/common/pages/change-log.vue': {
      routes:
        | '/common/change-log'
      views:
        | never
    }
    'src/ui/common/pages/features.vue': {
      routes:
        | '/common/features'
      views:
        | never
    }
    'src/ui/common/pages/help.vue': {
      routes:
        | '/common/help'
      views:
        | never
    }
    'src/ui/common/pages/privacy-policy.vue': {
      routes:
        | '/common/privacy-policy'
      views:
        | never
    }
    'src/ui/common/pages/terms-of-service.vue': {
      routes:
        | '/common/terms-of-service'
      views:
        | never
    }
    'src/ui/content-script-iframe/pages/index.vue': {
      routes:
        | '/content-script-iframe/'
      views:
        | never
    }
    'src/ui/devtools-panel/pages/index.vue': {
      routes:
        | '/devtools-panel/'
      views:
        | never
    }
    'src/ui/options-page/pages/index.vue': {
      routes:
        | '/options-page/'
      views:
        | never
    }
    'src/ui/setup/pages/install.vue': {
      routes:
        | '/setup/install'
      views:
        | never
    }
    'src/ui/setup/pages/update.vue': {
      routes:
        | '/setup/update'
      views:
        | never
    }
    'src/ui/side-panel/pages/index.vue': {
      routes:
        | '/side-panel/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
